export enum MicroservicesErrors {
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  ENCRYPTION_SERVICE_ERROR = 'ENCRYPTION_SERVICE_ERROR',
  USER_TOKEN_INVALID = 'USER_TOKEN_INVALID',
  USERNAME_IS_EXIST = 'USERNAME_IS_EXIST',
  EMAIL_IS_EXIST = 'EMAIL_IS_EXIST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_TOKEN_NOT_FOUND = 'USER_TOKEN_NOT_FOUND',
  AUTH_DATA_INVALID = 'AUTH_DATA_INVALID',
  USER_PASSWORD_MIS_MATCH = 'USER_PASSWORD_MIS_MATCH',
  UNAUTHORIZED = 'UNAUTHORIZED'
}
